/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 12:56:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import DB.Dbconnection;

public final class createAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("DB.Dbconnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/contact.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:35:11 GMT -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "preloader.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- preloader ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========== Mobile-nav section start here ========== -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mobileMenu.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- ========== Mobile-nav section end here ========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Header Section Starts Here========== -->\r\n");
      out.write("   	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- ==========Header Section Ends Here========== -->\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Page Header Section Start Here========== -->\r\n");
      out.write("    <section class=\"page-header-section service-title style-1\"\r\n");
      out.write("        style=\"background-image: url(assets/images/pageheader/pageheader.jpg)\">\r\n");
      out.write("        <div class=\"page-header-content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"page-header-content-inner\">\r\n");
      out.write("                    <div class=\"page-title\">\r\n");
      out.write("                        <h2>Create An Account</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <ol class=\"breadcrumb\">\r\n");
      out.write("                        <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("                        <li class=\"active\">Create An Account</li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Page Header Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--=============== Contact Us Section Start Here ========== -->\r\n");
      out.write("    <div class=\"contact-section\">\r\n");
      out.write("        <div class=\"contact-top padding-tb aside-bg padding-b\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8\">\r\n");
      out.write("                        <article class=\"contact-form-wrapper\">\r\n");
      out.write("                            <div class=\"\">\r\n");
      out.write("                                <h4>Savior - Saving Lives Through Organ Donation</h4>\r\n");
      out.write("                                <p class=\"mb-5\">\r\n");
      out.write("                                Welcome to Savior, an online platform dedicated to promoting organ donation and saving lives. \r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                 <form action=\"accountRegisterDb.jsp\" method=\"POST\" id=\"createAccount\" enctype=\"multipart/form-data\">\r\n");
      out.write("                                    <input type=\"text\" name=\"name\" placeholder=\"Name*\" required>\r\n");
      out.write("                                    <input type=\"email\" name=\"email\" placeholder=\"Email*\" required>\r\n");
      out.write("                                    <input type=\"tel\"  pattern=\"[0-9]{10}\" maxlength=\"12\"  title=\"Ten digits number\" name=\"mobileNo\" placeholder=\"Mobile Number*\" required>\r\n");
      out.write("                                    <label>Profile Pic*</label>\r\n");
      out.write("                                    <input type=\"file\" name=\"profile\" placeholder=\"Profile\" required>\r\n");
      out.write("                                    <label>Date of Birth</label>\r\n");
      out.write("                                    <input type=\"date\" name=\"dob\" placeholder=\"Date of Birth\" required>\r\n");
      out.write("									\r\n");
      out.write("									<select class=\"form-control mb-3\" name=\"gender\" id=\"AccountType\" required>\r\n");
      out.write("									<option value=\"\">Gender</option>\r\n");
      out.write("									<option value=\"Male\">Male</option>\r\n");
      out.write("									<option value=\"Female\">Female</option>\r\n");
      out.write("									</select>  \r\n");
      out.write("									\r\n");
      out.write("									<select class=\"form-control mb-3\" name=\"bloodgroup\"  id=\"bloodgroup\" required>\r\n");
      out.write("									<option value=\"\">Blood Group</option>\r\n");
      out.write("									");

									PreparedStatement ps=Dbconnection.getCon().prepareStatement("select * from bloodgroups");
									ResultSet rs=ps.executeQuery();
									while(rs.next()){
									
      out.write("\r\n");
      out.write("									<option value=\"");
      out.print(rs.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(2));
      out.write("</option>\r\n");
      out.write("									");
} 
									Dbconnection.con.close();
									
      out.write("\r\n");
      out.write("									</select>   \r\n");
      out.write("									           \r\n");
      out.write("									<select class=\"form-control mb-3\" name=\"AccountType\" id=\"AccountType\" required>\r\n");
      out.write("									<option value=\"\">Select Account Type</option>\r\n");
      out.write("									<option value=\"D\">Organ Donor</option>\r\n");
      out.write("									<option value=\"R\">Organ Recipient</option>\r\n");
      out.write("									</select>\r\n");
      out.write("									   \r\n");
      out.write("									  \r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"password\" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}\" title=\"Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters\"required>\r\n");
      out.write("                                    <input type=\"password\" name=\"cpassword\" id=\"cpassword\" placeholder=\"confirm password\" pattern=\"(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,}\" title=\"Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters\"required>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <textarea name=\"address\" cols=\"30\" rows=\"2\" placeholder=\"Address\" required></textarea>\r\n");
      out.write("                                     <p class=\"text-right\">Already have account? <a href=\"Login.jsp\" class=\"text-primary\">Login</a></p>\r\n");
      out.write("                                   \r\n");
      out.write("                                    <div class=\"button-msg d-flex flex-wrap justify-content-between align-items-center\">\r\n");
      out.write("                                        <button type=\" submit\" class=\"lab-btn\">\r\n");
      out.write("                                            <span>Create Account</span>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </form>\r\n");
      out.write("                                <p class=\"form-message mb-0\"></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </article>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <div class=\"contact-info-wrapper\">\r\n");
      out.write("                            <div class=\"contact-info-title\">\r\n");
      out.write("                                <h5>Get Information</h5>\r\n");
      out.write("                                <p>Our Contact information Details and\r\n");
      out.write("                                    Follow us on social media</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"contact-info-content\">\r\n");
      out.write("                                <div class=\"contact-info-item\">\r\n");
      out.write("                                    <div class=\"contact-info-inner\">\r\n");
      out.write("                                        <div class=\"contact-info-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/contact/01.png\" alt=\"address\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"contact-info-details\">\r\n");
      out.write("                                            <span class=\"fw-bold\">Office Address</span>\r\n");
      out.write("                                            <p>1201 park street, Fifth Avenue</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"contact-info-item\">\r\n");
      out.write("                                    <div class=\"contact-info-inner\">\r\n");
      out.write("                                        <div class=\"contact-info-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/contact/02.png\" alt=\"address\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"contact-info-details\">\r\n");
      out.write("                                            <span class=\"fw-bold\">Phone Number</span>\r\n");
      out.write("                                            <p>+22698 745 632,02 982 745</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"contact-info-item\">\r\n");
      out.write("                                    <div class=\"contact-info-inner\">\r\n");
      out.write("                                        <div class=\"contact-info-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/contact/03.png\" alt=\"address\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"contact-info-details\">\r\n");
      out.write("                                            <span class=\"fw-bold\">Send Mail</span>\r\n");
      out.write("                                            <p>yourmail@mail.com</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"contact-info-item\">\r\n");
      out.write("                                    <div class=\"contact-info-inner\">\r\n");
      out.write("                                        <div class=\"contact-info-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/contact/04.png\" alt=\"address\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"contact-info-details\">\r\n");
      out.write("                                            <span class=\"fw-bold\">Our Website</span>\r\n");
      out.write("                                            <p>www.yoursite.com</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ==========Contact Us Section ENding Here ============ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Map Section Start Here========== -->\r\n");
      out.write("    <div class=\"map-section\">\r\n");
      out.write("        <div class=\"map\">\r\n");
      out.write("        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d60572.37491795666!2d76.56696765!3d18.40315995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bcf83bd7132cd29%3A0x83629bac5848da3e!2sLatur%2C%20Maharashtra!5e0!3m2!1sen!2sin!4v1685667191549!5m2!1sen!2sin\" style=\"width:100%;height:100%\"  style=\"border:0;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>   \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ==========Map Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- scrollToTop start here -->\r\n");
      out.write("    <a href=\"#\" class=\"scrollToTop\"><i class=\"icofont-rounded-up\"></i></a>\r\n");
      out.write("    <!-- scrollToTop ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- All Scripts -->\r\n");
      out.write("    <script src=\"assets/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/circularProgressBar.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/hc-offcanvas-nav.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    $(\"#createAccount\").submit(function(e){\r\n");
      out.write("    	\r\n");
      out.write("    	let accountType=$(\"AccountType\").val();\r\n");
      out.write("    	let bg=$(\"#bloodgroup\").val();\r\n");
      out.write("    	let password=$(\"#password\").val();\r\n");
      out.write("    	let cpassword=$(\"#cpassword\").val();\r\n");
      out.write("    \r\n");
      out.write("    	if(accountType!=\"\" || accountType!=null )\r\n");
      out.write("    		{\r\n");
      out.write("    		if(bg!=\"\" || bg!=null)\r\n");
      out.write("    			{\r\n");
      out.write("    			if(password==cpassword)\r\n");
      out.write("    				{\r\n");
      out.write("    				return true;\r\n");
      out.write("    				}\r\n");
      out.write("    			\r\n");
      out.write("    		else{\r\n");
      out.write("    			alert(\"Password not matched\");\r\n");
      out.write("    			e.preventDefault();\r\n");
      out.write("    		}\r\n");
      out.write("    			}else{\r\n");
      out.write("        			alert(\"please select boodgroup\");\r\n");
      out.write("        			e.preventDefault();\r\n");
      out.write("        		}\r\n");
      out.write("    		}else{\r\n");
      out.write("    			alert(\"please select account type\");\r\n");
      out.write("    			e.preventDefault();\r\n");
      out.write("    		}\r\n");
      out.write("    	\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/contact.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:35:13 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
