/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 12:48:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  <!-- ==========Footer Section start Here========== -->\r\n");
      out.write("    <footer class=\"footer-section style-1 bg-color\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"footer-top padding-tb parallax-window4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 col-lg-6 wow fadeInUp order-lg-2\" data-wow-duration=\"1s\"\r\n");
      out.write("                            data-wow-delay=\".2s\">\r\n");
      out.write("                            <div class=\"footer-about\">\r\n");
      out.write("                                <div class=\"top\">\r\n");
      out.write("                                    <a href=\"index.jsp\" class=\"footer-logo\">\r\n");
      out.write("                                        <img src=\"assets/images/logo/logo3.png\" alt=\"footer-bottom\">\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <p>Proactive predominate empowere portals viaine robust infrastructurs Convenen simp\r\n");
      out.write("                                        scalable ntatves rather thanineri manetic action items Proactively predominate\r\n");
      out.write("                                        empowered portals robust</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"bottom\">\r\n");
      out.write("                                   \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 wow fadeInUp order-lg-1\" data-wow-duration=\"1s\"\r\n");
      out.write("                            data-wow-delay=\".1s\">\r\n");
      out.write("                            <div class=\"contact-info\">\r\n");
      out.write("                                <h3>Contact Info</h3>\r\n");
      out.write("                                <p>Rapidiously seize wireless strategic theme areas and corporate testing procedures.\r\n");
      out.write("                                    Uniquely</p>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><i class=\"icofont-home\"></i> Suite 02 New Jersey Road usa</li>\r\n");
      out.write("                                    <li><i class=\"icofont-phone\"></i> +880 142 258 123, 02-96936</li>\r\n");
      out.write("                                    <li><i class=\"icofont-envelope\"></i> <a href=\"#\"> info@example.com</a></li>\r\n");
      out.write("                                    <li><i class=\"icofont-globe\"></i> <a href=\"#\"> info@example.com</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 wow fadeInUp order-lg-3\" data-wow-duration=\"1s\"\r\n");
      out.write("                            data-wow-delay=\".4s\">\r\n");
      out.write("                             <div class=\"doctor-info mb-5 mb-sm-0\">\r\n");
      out.write("                                <h3>Our Doctors</h3>\r\n");
      out.write("                                <ul class=\"lab-ul\">\r\n");
      out.write("                                    <li><i class=\"icofont-double-right\"></i><a href=\"#\"> Dr. Nick Sims</a></li>\r\n");
      out.write("                                    <li><i class=\"icofont-double-right\"></i><a href=\"#\"> Dr. Michael Linden</a></li>\r\n");
      out.write("                                    <li><i class=\"icofont-double-right\"></i><a href=\"#\"> Dr. Max Turner</a></li>\r\n");
      out.write("                                    <li><i class=\"icofont-double-right\"></i><a href=\"#\"> Dr. Amy Adams</a></li>\r\n");
      out.write("                                    <li><i class=\"icofont-double-right\"></i><a href=\"#\"> Dr. Julia Jameson</a></li>\r\n");
      out.write("                                    <li><i class=\"icofont-double-right\"></i><a href=\"#\"> Dr. Michael Linden</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer-bottom\">\r\n");
      out.write("                    <div class=\"copyright text-center wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                        <span>Copyright &copy; 2021 <a href=\"index.html\">SAVIOR</a>. All rights reserved. by <a\r\n");
      out.write("                                href=\"\">SAVIOR</a></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- ==========Footer Section Ends Here========== -->\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
