/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 12:52:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import DB.Dbconnection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("DB.Dbconnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:33:48 GMT -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- preloader start here -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "preloader.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- preloader ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========== Mobile-nav section start here ========== -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mobileMenu.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- ========== Mobile-nav section end here ========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Header Section Starts Here========== -->\r\n");
      out.write("   	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- ==========Header Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Banner Section Start Here========== -->\r\n");
      out.write("    <section class=\"banner-section\">\r\n");
      out.write("        <div class=\"banner-slider\">\r\n");
      out.write("            <div class=\"swiper-wrapper\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"banner-item\" style=\"background-image: url(assets/images/banner/1.jpg);\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"banner-inner\">\r\n");
      out.write("                                <div class=\"row align-items-center\">\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <div class=\"banner-content\">\r\n");
      out.write("                                            <h2 class=\"wow fadeInDown\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">\r\n");
      out.write("                                               Savior\r\n");
      out.write("                                            </h2>\r\n");
      out.write("                                            <h1 class=\"wow fadeInLeft\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">\r\n");
      out.write("                                                <b>Give Life</b> Give Hope Be an Organ Donor\r\n");
      out.write("                                            </h1>\r\n");
      out.write("                                            <a href=\"#\" class=\"lab-btn wow fadeInUp\" data-wow-duration=\"2s\"\r\n");
      out.write("                                                data-wow-delay=\".1s\"><span>\r\n");
      out.write("                                                Be a Donor\r\n");
      out.write("                                                 <i class=\"icofont-rounded-double-right\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <div class=\"banner-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/banner/1.png\" alt=\"banner-img\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"banner-item\" style=\"background-image: url(assets/images/banner/1.jpg);\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"banner-inner\">\r\n");
      out.write("                                <div class=\"row align-items-center\">\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <div class=\"banner-content\">\r\n");
      out.write("                                            <h2 class=\"wow fadeInDown\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">\r\n");
      out.write("                                             Savior\r\n");
      out.write("                                            </h2>\r\n");
      out.write("                                            <h1 class=\"wow fadeInLeft\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">\r\n");
      out.write("                                                <b>\r\n");
      out.write("                                                    Be Someone's Miracle</b> Donate Your Organs\r\n");
      out.write("                                            </h1>\r\n");
      out.write("                                            <a href=\"#\" class=\"lab-btn wow fadeInUp\" data-wow-duration=\"2s\"\r\n");
      out.write("                                                data-wow-delay=\".1s\"><span> Be a Donor <i class=\"icofont-rounded-double-right\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <div class=\"banner-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/banner/2.png\" alt=\"banner-img\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"swiper-slide\">\r\n");
      out.write("                    <div class=\"banner-item\" style=\"background-image: url(assets/images/banner/1.jpg);\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"banner-inner\">\r\n");
      out.write("                                <div class=\"row align-items-center\">\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <div class=\"banner-content\">\r\n");
      out.write("                                            <h2 class=\"wow fadeInDown\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">  Savior\r\n");
      out.write("                                               \r\n");
      out.write("                                            </h2>\r\n");
      out.write("                                            <h1 class=\"wow fadeInLeft\" data-wow-duration=\"2s\" data-wow-delay=\".1s\">\r\n");
      out.write("                                                <b>Join the Life Chain:</b> Support Organ Donation\r\n");
      out.write("                                            </h1>\r\n");
      out.write("                                            <a href=\"#\" class=\"lab-btn wow fadeInUp\" data-wow-duration=\"2s\"\r\n");
      out.write("                                                data-wow-delay=\".1s\"><span>Be a Donor <i class=\"icofont-rounded-double-right\"></i></span>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <div class=\"banner-thumb\">\r\n");
      out.write("                                            <img src=\"assets/images/banner/3.png\" alt=\"banner-img\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"banner-pagination\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Banner Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Feature Section Start Here========== -->\r\n");
      out.write("    <section class=\"feature-section padding-tb bg-color\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"feature-section-wrapper\">\r\n");
      out.write("                <div class=\"section-header wow fadeInUp\" data-wow-delay=\"\" data-wow-duration=\"1s\">\r\n");
      out.write("                    <h2><span>We Offer Specialized</span> </h2>\r\n");
      out.write("                    <h2> Orthopedics To Meet Your Needs</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"section-content\">\r\n");
      out.write("                    <div class=\"row justify-content-center\">\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                            <div class=\"lab-item feature-item wow fadeInLeft\" data-wow-delay=\".2s\"\r\n");
      out.write("                                data-wow-duration=\"1s\">\r\n");
      out.write("                                <div class=\"lab-inner\">\r\n");
      out.write("                                    <div class=\"lab-thumb\">\r\n");
      out.write("                                        <img src=\"assets/images/feature/1.png\" alt=\"feature img\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"lab-content\">\r\n");
      out.write("                                        <h4>Medical Treatment</h4>\r\n");
      out.write("                                        <p>Medical Treatment\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <a href=\"#\" class=\"\"><span>Read More <i\r\n");
      out.write("                                                    class=\"icofont-rounded-double-right\"></i></span></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                            <div class=\"lab-item feature-item wow fadeInUp\" data-wow-delay=\".2s\" data-wow-duration=\"1s\">\r\n");
      out.write("                                <div class=\"lab-inner\">\r\n");
      out.write("                                    <div class=\"lab-thumb\">\r\n");
      out.write("                                        <img src=\"assets/images/feature/2.png\" alt=\"feature img\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"lab-content\">\r\n");
      out.write("                                        <h4>Emergency Help</h4>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amete consectetur adipisicing elite. vlote optio animi?\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <a href=\"#\" class=\"\"><span>Read More <i\r\n");
      out.write("                                                    class=\"icofont-rounded-double-right\"></i></span></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                            <div class=\"lab-item feature-item wow fadeInUp\" data-wow-delay=\".2s\" data-wow-duration=\"1s\">\r\n");
      out.write("                                <div class=\"lab-inner\">\r\n");
      out.write("                                    <div class=\"lab-thumb\">\r\n");
      out.write("                                        <img src=\"assets/images/feature/3.png\" alt=\"feature img\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"lab-content\">\r\n");
      out.write("                                        <h4>Medical Professionals</h4>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amete consectetur adipisicing elite. vlote optio animi?\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <a href=\"#\" class=\"\"><span>Read More <i\r\n");
      out.write("                                                    class=\"icofont-rounded-double-right\"></i></span></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                            <div class=\"lab-item feature-item wow fadeInRight\" data-wow-delay=\".2s\"\r\n");
      out.write("                                data-wow-duration=\"1s\">\r\n");
      out.write("                                <div class=\"lab-inner\">\r\n");
      out.write("                                    <div class=\"lab-thumb\">\r\n");
      out.write("                                        <img src=\"assets/images/feature/4.png\" alt=\"feature img\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"lab-content\">\r\n");
      out.write("                                        <h4>Qualified Doctors</h4>\r\n");
      out.write("                                        <p>Lorem ipsum dolor sit amete consectetur adipisicing elite. vlote optio animi?\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <a href=\"#\" class=\"\"><span>Read More <i\r\n");
      out.write("                                                    class=\"icofont-rounded-double-right\"></i></span></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Feature Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- ==========Counter Section Start Here========== -->\r\n");
      out.write("    <div class=\"counter-section style-1 padding-60\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"counter-item wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                    <div class=\"counter-item-inner\">\r\n");
      out.write("                        <div class=\"counter-thumb\">\r\n");
      out.write("                            <img src=\"assets/images/counter/01.png\" alt=\"counter\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"counter-content\">\r\n");
      out.write("                            <h3 class=\"number\"><span class=\"counter\">500</span></h3>\r\n");
      out.write("                            <p class=\"post-content\">Patients Every Day</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"counter-item wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\".2s\">\r\n");
      out.write("                    <div class=\"counter-item-inner\">\r\n");
      out.write("                        <div class=\"counter-thumb\">\r\n");
      out.write("                            <img src=\"assets/images/counter/02.png\" alt=\"counter\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"counter-content\">\r\n");
      out.write("                            <h3 class=\"number\"><span class=\"counter\">400</span></h3>\r\n");
      out.write("                            <p class=\"post-content\">Qualified Doctors</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"counter-item wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\".3s\">\r\n");
      out.write("                    <div class=\"counter-item-inner\">\r\n");
      out.write("                        <div class=\"counter-thumb\">\r\n");
      out.write("                            <img src=\"assets/images/counter/03.png\" alt=\"counter\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"counter-content\">\r\n");
      out.write("                            <h3 class=\"number\"><span class=\"counter\">12</span></h3>\r\n");
      out.write("                            <p class=\"post-content\">Years Experience</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"counter-item wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\".4s\">\r\n");
      out.write("                    <div class=\"counter-item-inner\">\r\n");
      out.write("                        <div class=\"counter-thumb\">\r\n");
      out.write("                            <img src=\"assets/images/counter/04.png\" alt=\"counter\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"counter-content\">\r\n");
      out.write("                            <h3 class=\"number\"><span class=\"counter\">350</span></h3>\r\n");
      out.write("                            <p class=\"post-content\">Diagnosis Verity</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ==========Counter Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- ==========Doctor Section Start Here========== -->\r\n");
      out.write("    <section class=\"doctor-section style-1 padding-tb\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                <h2><span>Meet Our</span></h2>\r\n");
      out.write("                <h2>Donors</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                  ");

                  
                  Dbconnection.getCon();
                  PreparedStatement ps=Dbconnection.con.prepareStatement("select distinct d.* from donor as d inner join donation as do on d.donor_id=do.donor_id order by d.donor_id desc limit 4");
                  ResultSet rs=ps.executeQuery();
                 while(rs.next()){
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                                    <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                        <div class=\"doctor-item style-1 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                            <div class=\"doctor-inner\">\r\n");
      out.write("                                <div class=\"doctor-thumb\">\r\n");
      out.write("                                    <img src=\"../");
      out.print(rs.getString(7));
      out.write("\" style=\"min-height: 290px;\" alt=\"donor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"doctor-content\">\r\n");
      out.write("                                    <div class=\"doctor-name\">\r\n");
      out.write("                                        <h4><a href=\"donorProfile.jsp?id=");
      out.print(rs.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(2));
      out.write("</a></h4>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <ul class=\"doctor-contact\">\r\n");
      out.write("                                        <li><span>Phone :</span>");
      out.print(rs.getString(6));
      out.write("</li>\r\n");
      out.write("                                        <li><span>Email :</span>");
      out.print(rs.getString(5));
      out.write("</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 ");
} 
      out.write("\r\n");
      out.write("                 </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"doctor-btn text-center wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".5s\">\r\n");
      out.write("                <a href=\"donor.jsp\" class=\"lab-btn\"><span> view all Donors <i\r\n");
      out.write("                            class=\"icofont-rounded-double-right\"></i></span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Doctor Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Doctor Section Start Here========== -->\r\n");
      out.write("    <section class=\"doctor-section style-1 padding-tb\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                <h2><span>Meet Our</span></h2>\r\n");
      out.write("                <h2>Medixin Professional Doctors</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                        <div class=\"doctor-item style-1 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                            <div class=\"doctor-inner\">\r\n");
      out.write("                                <div class=\"doctor-thumb\">\r\n");
      out.write("                                    <img src=\"assets/images/team/01.jpg\" alt=\"doctor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"doctor-content\">\r\n");
      out.write("                                    <div class=\"doctor-name\">\r\n");
      out.write("                                        <h4><a href=\"#\">Dr. Jason Kovalsky</a></h4>\r\n");
      out.write("                                        <p class=\"digi\">Cardiologist</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <ul class=\"doctor-contact\">\r\n");
      out.write("                                        <li><span>Phone :</span> 658 222 127 964</li>\r\n");
      out.write("                                        <li><span>Email :</span> info@example.com</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                        <div class=\"doctor-item style-1 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".2s\">\r\n");
      out.write("                            <div class=\"doctor-inner\">\r\n");
      out.write("                                <div class=\"doctor-thumb\">\r\n");
      out.write("                                    <img src=\"assets/images/team/02.jpg\" alt=\"doctor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"doctor-content\">\r\n");
      out.write("                                    <div class=\"doctor-name\">\r\n");
      out.write("                                        <h4><a href=\"#\">Patricia Mcneel</a></h4>\r\n");
      out.write("                                        <p class=\"digi\">Pediatrist</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <ul class=\"doctor-contact\">\r\n");
      out.write("                                        <li><span>Phone :</span> 658 222 127 964</li>\r\n");
      out.write("                                        <li><span>Email :</span> info@example.com</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                        <div class=\"doctor-item style-1 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".3s\">\r\n");
      out.write("                            <div class=\"doctor-inner\">\r\n");
      out.write("                                <div class=\"doctor-thumb\">\r\n");
      out.write("                                    <img src=\"assets/images/team/03.jpg\" alt=\"doctor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"doctor-content\">\r\n");
      out.write("                                    <div class=\"doctor-name\">\r\n");
      out.write("                                        <h4><a href=\"#\">William Khanna</a></h4>\r\n");
      out.write("                                        <p class=\"digi\">Throat Specialist</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <ul class=\"doctor-contact\">\r\n");
      out.write("                                        <li><span>Phone :</span> 658 222 127 964</li>\r\n");
      out.write("                                        <li><span>Email :</span> info@example.com</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xl-3 col-lg-4 col-md-6 col-12\">\r\n");
      out.write("                        <div class=\"doctor-item style-1 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".4s\">\r\n");
      out.write("                            <div class=\"doctor-inner\">\r\n");
      out.write("                                <div class=\"doctor-thumb\">\r\n");
      out.write("                                    <img src=\"assets/images/team/04.jpg\" alt=\"doctor\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"doctor-content\">\r\n");
      out.write("                                    <div class=\"doctor-name\">\r\n");
      out.write("                                        <h4><a href=\"#\">Eric Patterson</a></h4>\r\n");
      out.write("                                        <p class=\"digi\">Therapy</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <ul class=\"doctor-contact\">\r\n");
      out.write("                                        <li><span>Phone :</span> 658 222 127 964</li>\r\n");
      out.write("                                        <li><span>Email :</span> info@example.com</li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"doctor-btn text-center wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".5s\">\r\n");
      out.write("                <a href=\"doctor.jsp\" class=\"lab-btn\"><span> view all doctors <i\r\n");
      out.write("                            class=\"icofont-rounded-double-right\"></i></span></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Doctor Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Blog Section Start Here========== -->\r\n");
      out.write("    <section class=\"blog-section padding-tb bg-color\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                <h2><span>News Feed</span></h2>\r\n");
      out.write("                <h2>Be The First To New Stories</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <div class=\"col-12 col-md-6 col-xl-4 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                        <div class=\"post-item-inner\">\r\n");
      out.write("                            <div class=\"post-thumb\">\r\n");
      out.write("                                <a href=\"assets/images/blog/1.jpg\" data-rel=\"lightcase:myCollection\"><img\r\n");
      out.write("                                        src=\"assets/images/blog/1.jpg\" alt=\"blog post images\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"post-content\">\r\n");
      out.write("                                <span class=\"meta\">By <a href=\"#\">Admin</a> March 24, 2021</span>\r\n");
      out.write("                                <h4><a href=\"#\">Globa Empoer Extenve Chanels Extensve Creat Method</a></h4>\r\n");
      out.write("                                <p>Complete actuaze centi centrcing colora and sharin without anstaled anding bases\r\n");
      out.write("                                    aweme medicalplus Template.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog-footer\">\r\n");
      out.write("                                <a href=\"#\" class=\"viewall\">Read More <i class=\"icofont-double-right\"></i></a>\r\n");
      out.write("                                <a href=\"#\" class=\"blog-comment\"><i class=\"icofont-comment\"></i> 30</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-6 col-xl-4 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".2s\">\r\n");
      out.write("                        <div class=\"post-item-inner\">\r\n");
      out.write("                            <div class=\"post-thumb\">\r\n");
      out.write("                                <a href=\"assets/images/blog/2.jpg\" data-rel=\"lightcase:myCollection\"><img\r\n");
      out.write("                                        src=\"assets/images/blog/2.jpg\" alt=\"blog\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"post-content\">\r\n");
      out.write("                                <span class=\"meta\">By <a href=\"#\">Admin</a> March 4, 2021</span>\r\n");
      out.write("                                <h4><a href=\"#\">Why do you need dental check up regularly for better..</a></h4>\r\n");
      out.write("                                <p>Complete actuaze centi centrcing colora and sharin without anstaled anding bases\r\n");
      out.write("                                    aweme medicalplus Template.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog-footer\">\r\n");
      out.write("                                <a href=\"#\" class=\"viewall\">Read More <i class=\"icofont-double-right\"></i></a>\r\n");
      out.write("                                <a href=\"#\" class=\"blog-comment\"><i class=\"icofont-comment\"></i> 30</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12 col-md-6 col-xl-4 wow fadeInUp\" data-wow-duration=\"1s\" data-wow-delay=\".3s\">\r\n");
      out.write("                        <div class=\"post-item-inner\">\r\n");
      out.write("                            <div class=\"post-thumb\">\r\n");
      out.write("                                <a href=\"assets/images/blog/3.jpg\" data-rel=\"lightcase:myCollection\"><img\r\n");
      out.write("                                        src=\"assets/images/blog/3.jpg\" alt=\"blog\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"post-content\">\r\n");
      out.write("                                <span class=\"meta\">By <a href=\"#\">Admin</a> June 02, 2021</span>\r\n");
      out.write("                                <h4><a href=\"#\">Lorem ipsum dolor sit, amet consectetur adipisicing. </a></h4>\r\n");
      out.write("                                <p>Complete actuaze centi centrcing colora and sharin without anstaled anding bases\r\n");
      out.write("                                    aweme medicalplus Template.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"blog-footer\">\r\n");
      out.write("                                <a href=\"#\" class=\"viewall\">Read More <i class=\"icofont-double-right\"></i></a>\r\n");
      out.write("                                <a href=\"#\" class=\"blog-comment\"><i class=\"icofont-comment\"></i> 30</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Blog Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Newsletter Section Ends Here========== -->\r\n");
      out.write("    <section class=\"newsletter-section style-1\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"left wow fadeInLeft\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                    <div class=\"news-title\">\r\n");
      out.write("                        <h2>Saving Lives Together :</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> \r\n");
      out.write("                 <div class=\"right wow fadeInRight\" data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("                   <div class=\"news-title\">\r\n");
      out.write("                        <h2>Embrace Organ Donation</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>          \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Newsletter Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- scrollToTop start here -->\r\n");
      out.write("    <a href=\"#\" class=\"scrollToTop\"><i class=\"icofont-rounded-up\"></i></a>\r\n");
      out.write("    <!-- scrollToTop ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- All Scripts -->\r\n");
      out.write("    <script src=\"assets/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/circularProgressBar.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/hc-offcanvas-nav.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:34:31 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
