/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 12:58:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import DB.Dbconnection;
import java.sql.PreparedStatement;

public final class MyAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("DB.Dbconnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
Dbconnection.getCon(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:33:48 GMT -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- preloader start here -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "preloader.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- preloader ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ========== Mobile-nav section start here ========== -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mobileMenu.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- ========== Mobile-nav section end here ========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ==========Header Section Starts Here========== -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- ==========Header Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ==========Feature Section Start Here========== -->\r\n");
      out.write("	<section class=\"feature-section padding-tb bg-color\">\r\n");
      out.write("		<div class=\"container-fluid px-5\">\r\n");
      out.write("			<div class=\"feature-section-wrapper\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"section-content\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("							<div class=\"col-2\">\r\n");
      out.write("								<div class=\"list-group\" id=\"list-tab\" role=\"tablist\">\r\n");
      out.write("								\r\n");
      out.write("									");
if(session.getAttribute("userType").toString().toLowerCase().equals("d")){ 
      out.write("\r\n");
      out.write("									<a class=\"list-group-item list-group-item-action active\" id=\"list-home-list\" data-toggle=\"list\" href=\"#donate-organ\" role=\"tab\" aria-controls=\"home\">Donate Organ</a> \r\n");
      out.write("									<a class=\"list-group-item list-group-item-action \" id=\"myDonation-list\" data-toggle=\"list\" href=\"#mydonation\"role=\"tab\" aria-controls=\"profile\">My Donation</a>\r\n");
      out.write("									\r\n");
      out.write("									");
} 
      out.write("\r\n");
      out.write("									\r\n");
      out.write("									<a class=\"list-group-item list-group-item-action \" id=\"list-profile-list\" data-toggle=\"list\" href=\"#requestOrgan\"role=\"tab\" aria-controls=\"profile\">Find Donor</a>\r\n");
      out.write("									<a class=\"list-group-item list-group-item-action\" id=\"list-settings-list\" data-toggle=\"list\" href=\"#my-requests\" role=\"tab\" aria-controls=\"settings\">\r\n");
      out.write("									 ");
      out.print(session.getAttribute("userType").toString().toLowerCase().equals("d")?"Recipient's Request":"My Request Status" );
      out.write("\r\n");
      out.write("									     \r\n");
      out.write("									</a>\r\n");
      out.write("									<a class=\"list-group-item list-group-item-action \" id=\"list-profile-list\" href=\"");
      out.print(session.getAttribute("userType").toString().toLowerCase().equals("d")?"donorProfile.jsp":"reciepentProfile.jsp");
      out.write("?id=");
      out.print(session.getAttribute("userId"));
      out.write("\" aria-controls=\"profile\">Profile</a>\r\n");
      out.write("									\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-10\">\r\n");
      out.write("								<div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("									<div class=\"tab-pane fade show ");
      out.print((session.getAttribute("userType").toString().toLowerCase().equals("d"))?"active":"");
      out.write("\" id=\"donate-organ\"\r\n");
      out.write("										role=\"tabpanel\" aria-labelledby=\"list-home-list\">\r\n");
      out.write("										\r\n");
      out.write("												<form action=\"donateOrganDb.jsp\" method=\"post\">\r\n");
      out.write("											  <div class=\"form-group row\">\r\n");
      out.write("											    <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">Organs</label>\r\n");
      out.write("											   \r\n");
      out.write("											    <div class=\"col-sm-10\">\r\n");
      out.write("											     ");

											     PreparedStatement ps=Dbconnection.con.prepareStatement("select * from organ");
											     ResultSet rs=ps.executeQuery();
											     while(rs.next())
											     {
											     
      out.write("\r\n");
      out.write("											     <div class=\"form-check w-50\">\r\n");
      out.write("												  	<input class=\"form-check-input\" type=\"checkbox\" name=\"organs\" id=\"inlineCheckbox1\" value=\"");
      out.print(rs.getString(1));
      out.write("\">\r\n");
      out.write("												 	 <label class=\"form-check-label\" for=\"inlineCheckbox1\">");
      out.print(rs.getString(2));
      out.write("</label>\r\n");
      out.write("												</div>\r\n");
      out.write("											     ");

											     }
												     
      out.write("\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("												  <div class=\"form-group row\">\r\n");
      out.write("												    <label for=\"inputPassword3\" class=\"col-sm-3 col-form-label\">Cause of Death</label>\r\n");
      out.write("												    <div class=\"col-sm-8\">\r\n");
      out.write("												      <input type=\"text\" class=\"form-control\" id=\"inputPassword3\"  name=\"causeofDeath\" placeholder=\"Cause of Death\">\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("												  <div class=\"form-group row\">\r\n");
      out.write("												    <label for=\"inputPassword3\" class=\"col-sm-3 col-form-label\">Date of Death</label>\r\n");
      out.write("												    <div class=\"col-sm-8\">\r\n");
      out.write("												      <input type=\"date\" class=\"form-control\" id=\"inputPassword3\"  name=\"date\" placeholder=\"Cause of Death\">\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("												  <div class=\"form-group row\">\r\n");
      out.write("												    <label for=\"inputPassword3\" class=\"col-sm-3 col-form-label\">Guardian Name</label>\r\n");
      out.write("												    <div class=\"col-sm-8\">\r\n");
      out.write("												      <input type=\"text\" class=\"form-control\" id=\"inputPassword3\" name=\"gname\" placeholder=\"Guardian Name\">\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("												  <div class=\"form-group row\">\r\n");
      out.write("												    <label for=\"inputPassword3\" class=\"col-sm-3 col-form-label\">Guardian Contact</label>\r\n");
      out.write("												    <div class=\"col-sm-8\">\r\n");
      out.write("												      <input type=\"tel\" class=\"form-control\" id=\"inputPassword3\" name=\"gcontact\" placeholder=\"Mobile No\">\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("												  \r\n");
      out.write("												  <div class=\"form-group row\">\r\n");
      out.write("												    <div class=\"col-sm-10\">\r\n");
      out.write("												      <button type=\"submit\" class=\"btn btn-primary\">Donate</button>\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("												</form>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tab-pane fade show ");
      out.print((session.getAttribute("userType").toString().toLowerCase().equals("r"))?"active":"");
      out.write("\" id=\"requestOrgan\" role=\"tabpanel\"\r\n");
      out.write("										aria-labelledby=\"list-profile-list\">\r\n");
      out.write("										\r\n");
      out.write("											  <div class=\"form-group row\">\r\n");
      out.write("											    <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">Select Organ </label>\r\n");
      out.write("											    <select class=\"form-control mb-3\" id=\"Oid\">\r\n");
      out.write("											     ");

											      ps=Dbconnection.getCon().prepareStatement("select * from organ");
											      rs=ps.executeQuery();
											     while(rs.next())
											     {
											     
      out.write("\r\n");
      out.write("											    <option value=\"");
      out.print(rs.getString(1));
      out.write('"');
      out.write('>');
      out.print(rs.getString(2));
      out.write("</option>\r\n");
      out.write("											     ");

											     }
												     
      out.write("\r\n");
      out.write("												    </select> \r\n");
      out.write("												  <div class=\"form-group row\">\r\n");
      out.write("												    <div class=\"col-sm-10\">\r\n");
      out.write("												      <button type=\"button\" class=\"btn btn-primary\" onclick=\"searchDonar()\">Find Donor</button>\r\n");
      out.write("												    </div>\r\n");
      out.write("												  </div>\r\n");
      out.write("										</div>\r\n");
      out.write("										 <div class=\"form-group row\">\r\n");
      out.write("														\r\n");
      out.write("														<table class=\"table table-hover\">\r\n");
      out.write("														  <thead >\r\n");
      out.write("														    <tr>\r\n");
      out.write("														      <th scope=\"col\">Sr.No</th>\r\n");
      out.write("														      <th scope=\"col\">Donor Name and Contact</th>\r\n");
      out.write("														      <th scope=\"col\">Donor Age</th>\r\n");
      out.write("														      <th scope=\"col\">Organ</th>\r\n");
      out.write("														      <th scope=\"col\">Guardian Details</th>\r\n");
      out.write("														      ");
if(!session.getAttribute("userType").toString().toLowerCase().equals("d")){ 
      out.write("\r\n");
      out.write("														      <th scope=\"col\">Action</th>\r\n");
      out.write("														      ");
} 
      out.write("\r\n");
      out.write("														    </tr>\r\n");
      out.write("														  </thead>\r\n");
      out.write("														  <tbody id=\"donorsList\">\r\n");
      out.write("														   \r\n");
      out.write("														  </tbody>\r\n");
      out.write("														</table>\r\n");
      out.write("																										\r\n");
      out.write("												   </div>\r\n");
      out.write("	\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tab-pane fade show ");
      out.print((session.getAttribute("userType").toString().toLowerCase().equals("d"))?"":"");
      out.write("\" id=\"mydonation\" role=\"tabpanel\"\r\n");
      out.write("										aria-labelledby=\"list-profile-list\">\r\n");
      out.write("										\r\n");
      out.write("											  <div class=\"form-group row\">\r\n");
      out.write("											   \r\n");
      out.write("											    \r\n");
      out.write("											     ");

											      ps=Dbconnection.getCon().prepareStatement("select o.organ_name, do.donation_date,do.gaurdian_name,do.gaurdian_contact,do.cause_of_death from donation as do  inner join organ as o  on do.organ_id=o.organ_id where do.donor_id=?");
											      ps.setString(1,session.getAttribute("userId").toString());
											      rs=ps.executeQuery();
											     
      out.write("\r\n");
      out.write("												\r\n");
      out.write("				\r\n");
      out.write("										</div>\r\n");
      out.write("										 <div class=\"form-group row\">\r\n");
      out.write("														\r\n");
      out.write("														<table class=\"table table-hover\">\r\n");
      out.write("														  <thead >\r\n");
      out.write("														    <tr>\r\n");
      out.write("														      <th scope=\"col\">Sr.No</th>\r\n");
      out.write("														      <th scope=\"col\">Donated Organ</th>\r\n");
      out.write("														      <th scope=\"col\">Donated Date</th>\r\n");
      out.write("														      <th scope=\"col\">Cause of Date</th>														      \r\n");
      out.write("														      <th scope=\"col\">Guardian Details</th>\r\n");
      out.write("														    </tr>\r\n");
      out.write("														  </thead>\r\n");
      out.write("														  <tbody id=\"donotedsList\">\r\n");
      out.write("														   	");

														   	int i=1;
														   	while(rs.next()){ 
      out.write("\r\n");
      out.write("														   	 <tr>\r\n");
      out.write("														   	  <td scope=\"col\">");
      out.print(i);
      out.write("</td>\r\n");
      out.write("														   	  <td scope=\"col\">");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("														   	  <td scope=\"col\">");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("														   	  <td scope=\"col\">");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("														   	  <td scope=\"col\">\r\n");
      out.write("														   	  	<p>");
      out.print(rs.getString(3));
      out.write("</p>\r\n");
      out.write("														   	  	<p>");
      out.print(rs.getString(4));
      out.write("</p>\r\n");
      out.write("														   	  	\r\n");
      out.write("														   	  	</td>\r\n");
      out.write("														   	 </tr>\r\n");
      out.write("														   	");
} 
      out.write("\r\n");
      out.write("														  </tbody>\r\n");
      out.write("														</table>\r\n");
      out.write("																										\r\n");
      out.write("												   </div>\r\n");
      out.write("	\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"tab-pane fade\" id=\"my-requests\" role=\"tabpanel\"\r\n");
      out.write("										aria-labelledby=\"list-settings-list\">\r\n");
      out.write("										<div class=\"form-group row\">\r\n");
      out.write("										<div class=\"col-12\">\r\n");
      out.write("										<h3>\r\n");
      out.write("										 ");
      out.print(session.getAttribute("userType").toString().toLowerCase().equals("d")?"Recipient's Request":"My Requests" );
      out.write("\r\n");
      out.write("														     \r\n");
      out.write("										</h3>\r\n");
      out.write("										<table class=\"table table-hover\">\r\n");
      out.write("														  <thead >\r\n");
      out.write("														    <tr>\r\n");
      out.write("														      <th scope=\"col\">Sr.No</th>\r\n");
      out.write("														      <th scope=\"col\">\r\n");
      out.write("														      ");
      out.print(session.getAttribute("userType").toString().toLowerCase().equals("d")?"Recipient Name and Contact":"Donor Name and Contact" );
      out.write("\r\n");
      out.write("														      \r\n");
      out.write("														      </th>\r\n");
      out.write("														      \r\n");
      out.write("														      <th scope=\"col\">\r\n");
      out.write("														       ");
      out.print(session.getAttribute("userType").toString().toLowerCase().equals("d")?"Recipient Age":"Donor Age" );
      out.write("\r\n");
      out.write("														     \r\n");
      out.write("														      </th>\r\n");
      out.write("														      \r\n");
      out.write("														      <th scope=\"col\">Organ</th>\r\n");
      out.write("														    ");
  if(!(session.getAttribute("userType").toString().toLowerCase().equals("d"))){
      out.write("\r\n");
      out.write("														      <th scope=\"col\">Guardian Details</th>\r\n");
      out.write("														      ");
} 
      out.write("\r\n");
      out.write("														      <th scope=\"col\">Transplantation Location</th>\r\n");
      out.write("														      <th scope=\"col\">Transplantation Date</th>\r\n");
      out.write("														      <th scope=\"col\">Transplantation Status</th>\r\n");
      out.write("														    </tr>\r\n");
      out.write("														  </thead>\r\n");
      out.write("														  <tbody id=\"donorsList\">\r\n");
      out.write("														   ");

														   String query=(session.getAttribute("userType").toString().toLowerCase().equals("d"))?														
														   "select r.Recipient_name,r.Recipient_contact,FLOOR((TIMESTAMPDIFF(MONTH, r.Recipient_dob, CURDATE()) / 12)) as Age,do.gaurdian_name,do.gaurdian_contact,o.organ_name,t.transplantation_location,t.transplantation_date,t.status,t.transplantation_id from transplantation as t inner join donation as do on t.donation_id=do.donation_id inner join donor as d on d.donor_id=do.donor_id inner join  organ as o on o.organ_id=do.organ_id inner join recipient as r on t.recipient_id=r.Recipient_id where d.donor_id=?"
														   :"select d.donor_name,d.donor_contact,FLOOR((TIMESTAMPDIFF(MONTH, d.donor_dob, CURDATE()) / 12)) as Age,do.gaurdian_name,do.gaurdian_contact,o.organ_name,t.transplantation_location,t.transplantation_date,t.status from transplantation as t inner join donation as do on t.donation_id=do.donation_id inner join donor as d on d.donor_id=do.donor_id inner join  organ as o on o.organ_id=do.organ_id inner join recipient as r on t.recipient_id=r.Recipient_id where t.recipient_id=?";
														   
														   
														   
														   ps=Dbconnection.con.prepareStatement(query);
														   ps.setString(1,session.getAttribute("userId").toString());
														   rs=ps.executeQuery();
														    i=1;
														   while(rs.next())
														   {
														   
      out.write("\r\n");
      out.write("														    <tr>\r\n");
      out.write("														    	<td scope=\"col\">");
      out.print(i );
      out.write("</td>\r\n");
      out.write("														    	<td scope=\"col\">\r\n");
      out.write("														    					<p>");
      out.print(rs.getString(1) );
      out.write("</p>\r\n");
      out.write("														    					<p>");
      out.print(rs.getString(2) );
      out.write("</p>														    					\r\n");
      out.write("														    					</td>\r\n");
      out.write("														    	<td scope=\"col\">");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("														    	<td scope=\"col\">");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("														    	");
 if(!(session.getAttribute("userType").toString().toLowerCase().equals("d"))){
      out.write("\r\n");
      out.write("														    	<td scope=\"col\">\r\n");
      out.write("														    		<p>");
      out.print(rs.getString(4) );
      out.write("</p>\r\n");
      out.write("														    	    <p>");
      out.print(rs.getString(5) );
      out.write("</p>\r\n");
      out.write("														    	</td>\r\n");
      out.write("														    	");
} 
      out.write("\r\n");
      out.write("														    	<td scope=\"col\">");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("														    	<td scope=\"col\">");
      out.print(rs.getString(8));
      out.write("</td>\r\n");
      out.write("														    	\r\n");
      out.write("														    	\r\n");
      out.write("														    	<td scope=\"col\">\r\n");
      out.write("														    	");
 if((session.getAttribute("userType").toString().toLowerCase().equals("d"))){
      out.write("\r\n");
      out.write("														    	\r\n");
      out.write("														    	<select id=\"status\" class=\"form-control rstatus\" transplantId=\"");
      out.print(rs.getString(10) );
      out.write("\" >\r\n");
      out.write("														    	<option value=\"Pending\" ");
      out.print((rs.getString(9).equals("Pending"))?"selected":"");
      out.write(">Pending</option>\r\n");
      out.write("														    	<option value=\"Approved\" ");
      out.print((rs.getString(9).equals("Approved"))?"selected":"");
      out.write(">Approved</option>\r\n");
      out.write("														    	<option value=\"Rejected\" ");
      out.print((rs.getString(9).equals("Rejected"))?"selected":"");
      out.write(">Rejected</option>\r\n");
      out.write("														    	</select>\r\n");
      out.write("														    	");
}else{ 
      out.write("\r\n");
      out.write("																");
      out.print((rs.getString(9).equals("Pending"))?"<p class='btn btn-sm btn-warning'>"+rs.getString(9)+"</p>":
																	(rs.getString(9).equals("Approved"))?"<p class='btn btn-sm btn-success'>"+rs.getString(9)+"</p>":
																	(rs.getString(9).equals("Rejected"))?"<p class='btn btn-sm btn-danger'>"+rs.getString(9)+"</p>":""
																);
      out.write("\r\n");
      out.write("														    \r\n");
      out.write("														    	");
} 
      out.write("\r\n");
      out.write("														    	\r\n");
      out.write("														    	");
} 
      out.write("\r\n");
      out.write("														    	</td>\r\n");
      out.write("														    </tr>\r\n");
      out.write("														   ");

														   
      out.write("\r\n");
      out.write("														  </tbody>\r\n");
      out.write("														</table>\r\n");
      out.write("										</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										</div>\r\n");
      out.write("								</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ==========Feature Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- ==========Footer Section Ends Here========== -->\r\n");
      out.write("	<section class=\"footer-section style-1\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"section-wrapper\">\r\n");
      out.write("				<div class=\"footer-top\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-12 col-sm-6 col-xl-3 wow fadeInUp\"\r\n");
      out.write("							data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("							<div class=\"contact-info\">\r\n");
      out.write("								<h3>Contact Info</h3>\r\n");
      out.write("								<p>Rapidiously seize wireless strategic theme areas and\r\n");
      out.write("									corporate testing procedures. Uniquely</p>\r\n");
      out.write("								<ul class=\"lab-ul\">\r\n");
      out.write("									<li><i class=\"icofont-home\"></i> Suite 02 New Jersey Road\r\n");
      out.write("										usa</li>\r\n");
      out.write("									<li><i class=\"icofont-phone\"></i> +880 142 258 123,\r\n");
      out.write("										02-96936</li>\r\n");
      out.write("									<li><i class=\"icofont-envelope\"></i> <a href=\"#\">\r\n");
      out.write("											info@example.com</a></li>\r\n");
      out.write("									<li><i class=\"icofont-globe\"></i> <a href=\"#\">\r\n");
      out.write("											info@example.com</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12 col-sm-6 col-xl-3 wow fadeInUp\"\r\n");
      out.write("							data-wow-duration=\"1s\" data-wow-delay=\".2s\">\r\n");
      out.write("							<div class=\"doctor-info mb-5 mb-sm-0\">\r\n");
      out.write("								<h3>Our Doctors</h3>\r\n");
      out.write("								<ul class=\"lab-ul\">\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">\r\n");
      out.write("											Dr. Nick Sims</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">\r\n");
      out.write("											Dr. Michael Linden</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">\r\n");
      out.write("											Dr. Max Turner</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">\r\n");
      out.write("											Dr. Amy Adams</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">\r\n");
      out.write("											Dr. Julia Jameson</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">\r\n");
      out.write("											Dr. Michael Linden</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12 col-sm-6 col-xl-3 wow fadeInUp\"\r\n");
      out.write("							data-wow-duration=\"1s\" data-wow-delay=\".3s\">\r\n");
      out.write("							<div class=\"service-info  mb-5 mb-sm-0\">\r\n");
      out.write("								<h3>Our Services</h3>\r\n");
      out.write("								<ul class=\"lab-ul\">\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">Outpatient\r\n");
      out.write("											Surgery</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">Cardiac\r\n");
      out.write("											Clinic</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">Ophthalmology\r\n");
      out.write("											Clinic</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">Gynaecological\r\n");
      out.write("											Clinic</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">Outpatient\r\n");
      out.write("											Rehabilitation</a></li>\r\n");
      out.write("									<li><i class=\"icofont-double-right\"></i><a href=\"#\">Ophthalmology\r\n");
      out.write("											Clinic</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-12 col-sm-6 col-xl-3 wow fadeInUp\"\r\n");
      out.write("							data-wow-duration=\"1s\" data-wow-delay=\".4s\">\r\n");
      out.write("							<div class=\"time-info\">\r\n");
      out.write("								<h3>opening hours</h3>\r\n");
      out.write("								<div class=\"dep-item\">\r\n");
      out.write("									<div class=\"dep-item-inner d-flex justify-content-between\">\r\n");
      out.write("										<div class=\"day-name\">Satarday</div>\r\n");
      out.write("										<div class=\"day-time\">8:00 am-10:00 pm</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"dep-item\">\r\n");
      out.write("									<div class=\"dep-item-inner d-flex justify-content-between\">\r\n");
      out.write("										<div class=\"day-name\">Sunday</div>\r\n");
      out.write("										<div class=\"day-time\">6:00 am-8:00 pm</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"dep-item\">\r\n");
      out.write("									<div class=\"dep-item-inner d-flex justify-content-between\">\r\n");
      out.write("										<div class=\"day-name\">Monday</div>\r\n");
      out.write("										<div class=\"day-time\">6:00 am-2:00 pm</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"dep-item\">\r\n");
      out.write("									<div class=\"dep-item-inner d-flex justify-content-between\">\r\n");
      out.write("										<div class=\"day-name\">Tuesday</div>\r\n");
      out.write("										<div class=\"day-time\">7:00 am-9:00 pm</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"dep-item\">\r\n");
      out.write("									<div class=\"dep-item-inner d-flex justify-content-between\">\r\n");
      out.write("										<div class=\"day-name\">Widnessday</div>\r\n");
      out.write("										<div class=\"day-time\">10:00 am-12:00 pm</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"dep-item\">\r\n");
      out.write("									<div class=\"dep-item-inner d-flex justify-content-between\">\r\n");
      out.write("										<div class=\"day-name\">Thirsday</div>\r\n");
      out.write("										<div class=\"day-time\">2:00 am-6:00 pm</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-bottom\">\r\n");
      out.write("					<div class=\"copyright text-center wow fadeInUp\"\r\n");
      out.write("						data-wow-duration=\"1s\" data-wow-delay=\".1s\">\r\n");
      out.write("						<span>Copyright &copy; 2021 <a href=\"index.html\">Medixin</a>.\r\n");
      out.write("							Designed by <a\r\n");
      out.write("							href=\"https://www.templatemonster.com/authors/labartisan/\">LabArtisan</a></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- ==========Footer Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("	<!-- scrollToTop start here -->\r\n");
      out.write("	<a href=\"#\" class=\"scrollToTop\"><i class=\"icofont-rounded-up\"></i></a>\r\n");
      out.write("	<!-- scrollToTop ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- All Scripts -->\r\n");
      out.write("	<script src=\"assets/js/jquery.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/swiper.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/wow.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/circularProgressBar.min.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/hc-offcanvas-nav.js\"></script>\r\n");
      out.write("	<script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		function searchDonar()\r\n");
      out.write("		{\r\n");
      out.write("			let Oid=$(\"#Oid\").val();\r\n");
      out.write("			 $.ajax({\r\n");
      out.write("			        type: \"POST\",\r\n");
      out.write("			        url: \"searchDonar.jsp\",\r\n");
      out.write("			        data:\"id=\"+Oid, // serializes the form's elements.\r\n");
      out.write("			        success: function(data)\r\n");
      out.write("			        {\r\n");
      out.write("			          $(\"#donorsList\").html(data);\r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function ask(id,organName)\r\n");
      out.write("		{\r\n");
      out.write("			if(Confirm=confirm(\"Are you sure to ask for Donate\"+organName))\r\n");
      out.write("				{\r\n");
      out.write("				location.href=\"transplantation.jsp?did=\"+id;\r\n");
      out.write("				}	\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$('.rstatus').change(function()\r\n");
      out.write("		{\r\n");
      out.write("			let status=$(this).val();\r\n");
      out.write("			let id=$(this).attr(\"transplantId\");\r\n");
      out.write("			\r\n");
      out.write("			 $.ajax({\r\n");
      out.write("			        type: \"POST\",\r\n");
      out.write("			        url: \"updateStatusDb.jsp\",\r\n");
      out.write("			        data:\"id=\"+id+\"&status=\"+status, // serializes the form's elements.\r\n");
      out.write("			        success: function(data)\r\n");
      out.write("			        {\r\n");
      out.write("			         alert(\"Status Updated Successfully\");\r\n");
      out.write("			         \r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:34:31 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
