/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 12:58:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import DB.Dbconnection;
import java.sql.PreparedStatement;

public final class reciepentProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("DB.Dbconnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:33:48 GMT -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- preloader start here -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "preloader.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- preloader ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ========== Mobile-nav section start here ========== -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "mobileMenu.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- ========== Mobile-nav section end here ========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- ==========Header Section Starts Here========== -->\r\n");
      out.write("   	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!-- ==========Header Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <!-- ==========Doctor Section Start Here========== -->\r\n");
      out.write("    <section class=\"doctor-section style-2 padding-tb\" style=\"background-image: url(assets/images/service/bg.jpg); background-size: cover;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"section-wrapper\">\r\n");
      out.write("                <div class=\"row no-gutters\">\r\n");
      out.write("                    \r\n");
      out.write("                    ");

                    Dbconnection.getCon();
                    PreparedStatement ps=Dbconnection.con.prepareStatement("select distinct d.*,b.BloodGroupName from recipient as d inner join bloodgroups as b on d.blood_category=b.id where d.Recipient_id=?");
                    ps.setString(1,request.getParameter("id"));
                    ResultSet rs=ps.executeQuery();
                    
                    while(rs.next()){
      out.write("\r\n");
      out.write("                    <div class=\"col-lg-10 col-12 bg-white p-3 shadow\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                    	<div class=\"col-4\">\r\n");
      out.write("                        <div class=\"service-item\">\r\n");
      out.write("                            <div class=\"service-thumb\">\r\n");
      out.write("                               <img src=\"../");
      out.print(rs.getString(7));
      out.write("\" style=\"min-height: 290px;\" alt=\"donor\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           </div>\r\n");
      out.write("                           <div class=\"col-8\">\r\n");
      out.write("                            <div class=\"service-content\" style=\"position: absolute;\">\r\n");
      out.write("                                \r\n");
      out.write("                                <h4>");
      out.print(rs.getString(2));
      out.write("</h4>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6 text-right\"><b>Date of Birth : </b></div><div class=\"col-6\">");
      out.print(rs.getString(4));
      out.write("</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6 text-right\"><b>Blood Group : </b></div><div class=\"col-6\">");
      out.print(rs.getString("BloodGroupName"));
      out.write("</div>\r\n");
      out.write("                               </div>\r\n");
      out.write("                               <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6 text-right\"><b>Mobile Number: </b></div><div class=\"col-6\">");
      out.print(rs.getString(6));
      out.write("</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6 text-right\"><b>Email Id : </b></div><div class=\"col-6\">");
      out.print(rs.getString(5));
      out.write("</div>\r\n");
      out.write("                               </div>\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-6 text-right\"><b>Address : </b></div><div class=\"col-6\">");
      out.print(rs.getString(8));
      out.write("</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- ==========Doctor Section Ends Here========== -->\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- scrollToTop start here -->\r\n");
      out.write("    <a href=\"#\" class=\"scrollToTop\"><i class=\"icofont-rounded-up\"></i></a>\r\n");
      out.write("    <!-- scrollToTop ending here -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- All Scripts -->\r\n");
      out.write("    <script src=\"assets/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/swiper.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/wow.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/circularProgressBar.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/hc-offcanvas-nav.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/functions.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Mirrored from labartisan.net/demo/template/medixin/medixin/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 25 May 2023 19:34:31 GMT -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
