/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 13:07:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import DB.Dbconnection;
import java.sql.PreparedStatement;

public final class donor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("DB.Dbconnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("    <body class=\"dark-sidenav\">\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("	   <div class=\"page-wrapper\">\r\n");
      out.write("	   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topbar.jsp", out, false);
      out.write("\r\n");
      out.write("	   \r\n");
      out.write("	   ");

	   Dbconnection.getCon();
	   
      out.write("\r\n");
      out.write("	      <div class=\"row my-5\">\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"card\">\r\n");
      out.write("                                <div class=\"card-header\">\r\n");
      out.write("                                    <h4 class=\"card-title\">Donor List</h4>\r\n");
      out.write("                                </div><!--end card-header-->\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <div class=\"table-rep-plugin\">\r\n");
      out.write("                                        <div class=\"table-responsive mb-0\" data-pattern=\"priority-columns\">\r\n");
      out.write("                                            <table id=\"tech-companies-1\" class=\"table table-striped mb-0\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                <tr>\r\n");
      out.write("                                                	<th>Sr.No</th>\r\n");
      out.write("                                                    <th>Donor Name</th>\r\n");
      out.write("                                                    <th data-priority=\"1\">Mobile No</th>\r\n");
      out.write("                                                    <th data-priority=\"2\">Email Id</th>\r\n");
      out.write("                                                    <th data-priority=\"3\">Blood Group</th>\r\n");
      out.write("                                                    <th data-priority=\"1\">Date of Birth</th> \r\n");
      out.write("                                                    <th data-priority=\"1\">Age</th> \r\n");
      out.write("                                                    <th data-priority=\"1\">Status</th> \r\n");
      out.write("                                                    <th data-priority=\"1\">\r\n");
      out.write("                                                    Action\r\n");
      out.write("                                                    </th> \r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                ");

                                                PreparedStatement ps=Dbconnection.con.prepareStatement("select b.BloodGroupName,d.*,FLOOR((TIMESTAMPDIFF(MONTH, d.donor_dob, CURDATE()) / 12)) as Age from donor as d inner join bloodgroups as b on d.blood_category=b.id");
                                              	ResultSet rs=ps.executeQuery();
                                              	int i=0;
                                              	while(rs.next()){
                                                
      out.write("\r\n");
      out.write("                                                 <tr>\r\n");
      out.write("                                                    <td>");
      out.print(++i);
      out.write("</th>\r\n");
      out.write("                                                    <td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("                                                    <td data-priority=\"1\">");
      out.print(rs.getString(7) );
      out.write("</td>\r\n");
      out.write("                                                    <td data-priority=\"2\">");
      out.print(rs.getString(6) );
      out.write("</td>\r\n");
      out.write("                                                    <td data-priority=\"3\">");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("                                                    <td data-priority=\"1\">");
      out.print(rs.getString(5));
      out.write("</td> \r\n");
      out.write("                                                    <td data-priority=\"1\">");
      out.print(rs.getString("Age"));
      out.write("</td> \r\n");
      out.write("                                                    <td data-priority=\"1\">\r\n");
      out.write("                                                    <span class=\"badge shadow bg-");
      out.print((rs.getString("status").equals("Active"))?"success":"danger");
      out.write("\">\r\n");
      out.write("                                                     ");
      out.print(rs.getString("status"));
      out.write("\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                    </td> \r\n");
      out.write("                                                    <td class=\"text-right\">\r\n");
      out.write("                                                    <select onchange=\"updatStatus(");
      out.print(rs.getString(2) );
      out.write(",this.value)\">\r\n");
      out.write("                                                    	<option value=\"Active\" ");
      out.print((rs.getString("status").equals("Active")?"selected":""));
      out.write(">Active</option>\r\n");
      out.write("                                                    	<option value=\"Inactive\" ");
      out.print((rs.getString("status").equals("Inactive")?"selected":""));
      out.write(">Inactive</option>                                                    	\r\n");
      out.write("                                                    </select>\r\n");
      out.write("                                                	</td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                                ");
} 
      out.write("\r\n");
      out.write("                                             </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                        </div>    \r\n");
      out.write("                                    </div>    \r\n");
      out.write("                                </div><!--end card-body-->\r\n");
      out.write("                            </div><!--end card-->\r\n");
      out.write("                        </div> <!-- end col -->\r\n");
      out.write("                    </div> <!-- end row -->\r\n");
      out.write("	   \r\n");
      out.write("	   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	   </div>\r\n");
      out.write("	   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "assetLinks.jsp", out, false);
      out.write("\r\n");
      out.write("	   <script>\r\n");
      out.write("	   	function updatStatus(id,a)\r\n");
      out.write("	   	{\r\n");
      out.write("	   		\r\n");
      out.write("			 $.ajax({\r\n");
      out.write("			        type: \"POST\",\r\n");
      out.write("			        url: \"updateUserStatusDb.jsp\",\r\n");
      out.write("			        data:\"id=\"+id+\"&status=\"+a+\"&userType=d\", // serializes the form's elements.\r\n");
      out.write("			        success: function(data)\r\n");
      out.write("			        {\r\n");
      out.write("			         alert(data.trim());\r\n");
      out.write("			         location.reload();\r\n");
      out.write("			         \r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("	   	}\r\n");
      out.write("	   </script>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
