/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 13:07:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import DB.Dbconnection;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("DB.Dbconnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Left Sidenav -->\r\n");
      out.write("        <div class=\"left-sidenav\">\r\n");
      out.write("            <!-- LOGO -->\r\n");
      out.write("            <div class=\"brand\">\r\n");
      out.write("                <a href=\"index.jsp\" class=\"logo\">\r\n");
      out.write("                 <h3><span class=\"text-white\">Organ</span> <span class=\"text-primary\"> Donation</span></h3>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

            Dbconnection.getCon();
            PreparedStatement ps=null;
            ResultSet rs=null;
            
      out.write("\r\n");
      out.write("            <!--end logo-->\r\n");
      out.write("            <div class=\"menu-content h-100\" data-simplebar>\r\n");
      out.write("                <ul class=\"metismenu left-sidenav-menu\">\r\n");
      out.write("                    <li class=\"menu-label mt-0\">Main</li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"index.jsp\"> <i data-feather=\"home\" class=\"align-self-center menu-icon\"></i><span>Dashboard</span><span class=\"menu-arrow\"></span></a>  \r\n");
      out.write("                    </li>\r\n");
      out.write("    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript: void(0);\"><i data-feather=\"grid\" class=\"align-self-center menu-icon\"></i><span>Donor</span><span class=\"menu-arrow\"><i class=\"mdi mdi-chevron-right\"></i></span></a>\r\n");
      out.write("                        <ul class=\"nav-second-level\" aria-expanded=\"false\">\r\n");
      out.write("                           \r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"donor.jsp\"><i class=\"ti-control-record\"></i>All Donors</a></li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"donationList.jsp\"><i class=\"ti-control-record\"></i>All Organ Donation list</a></li>\r\n");
      out.write("                         \r\n");
      out.write("                         	");

                         	ps=Dbconnection.con.prepareStatement("select * from organ");
                         	rs=ps.executeQuery();
                         	while(rs.next())
                         	{
      out.write("\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"donationList.jsp?id=");
      out.print(rs.getString(1));
      out.write("&name=");
      out.print(rs.getString(2));
      out.write("\"><i class=\"ti-control-record\"></i>");
      out.print(rs.getString(2));
      out.write(" Donor List</a></li>\r\n");
      out.write("                            ");
} 
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li> \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript: void(0);\"><i data-feather=\"grid\" class=\"align-self-center menu-icon\"></i><span>Recipient's</span><span class=\"menu-arrow\"><i class=\"mdi mdi-chevron-right\"></i></span></a>\r\n");
      out.write("                        <ul class=\"nav-second-level\" aria-expanded=\"false\">\r\n");
      out.write("                           \r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"recipient.jsp\"><i class=\"ti-control-record\"></i>All Recipient's</a></li>                           \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li> \r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"javascript: void(0);\"><i data-feather=\"grid\" class=\"align-self-center menu-icon\"></i><span>Transplantation</span><span class=\"menu-arrow\"><i class=\"mdi mdi-chevron-right\"></i></span></a>\r\n");
      out.write("                        <ul class=\"nav-second-level\" aria-expanded=\"false\">\r\n");
      out.write("                           \r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"transplantation.jsp\"><i class=\"ti-control-record\"></i>All Transplantation</a></li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"transplantation.jsp?id=Pending\"><i class=\"ti-control-record\"></i>Pending Transplantation</a></li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"transplantation.jsp?id=Approved\"><i class=\"ti-control-record\"></i>Approved Transplantation</a></li>\r\n");
      out.write("                            <li class=\"nav-item\"><a class=\"nav-link\" href=\"transplantation.jsp?id=Rejected\"><i class=\"ti-control-record\"></i>Rejected Transplantation</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li> \r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end left-sidenav-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
