/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-04 13:07:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  <!-- Top Bar Start -->\r\n");
      out.write("            <div class=\"topbar\">            \r\n");
      out.write("                <!-- Navbar -->\r\n");
      out.write("                <nav class=\"navbar-custom\">    \r\n");
      out.write("                    <ul class=\"list-unstyled topbar-nav float-end mb-0\">  \r\n");
      out.write("                        <li class=\"dropdown hide-phone\">\r\n");
      out.write("                           \r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-end dropdown-lg p-0\">\r\n");
      out.write("                                <!-- Top Search Bar -->\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>                      \r\n");
      out.write("\r\n");
      out.write("                        <li class=\"dropdown notification-list\">\r\n");
      out.write("                           \r\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-end dropdown-lg pt-0\">\r\n");
      out.write("                            \r\n");
      out.write("                                <h6 class=\"dropdown-item-text font-15 m-0 py-3 border-bottom d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                    Notifications <span class=\"badge bg-primary rounded-pill\">2</span>\r\n");
      out.write("                                </h6> \r\n");
      out.write("                                <div class=\"notification-menu\" data-simplebar>\r\n");
      out.write("                                    <!-- item-->\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item py-3\">\r\n");
      out.write("                                        <small class=\"float-end text-muted ps-2\">2 min ago</small>\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <div class=\"avatar-md bg-soft-primary\">\r\n");
      out.write("                                                <i data-feather=\"shopping-cart\" class=\"align-self-center icon-xs\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body align-self-center ms-2 text-truncate\">\r\n");
      out.write("                                                <h6 class=\"my-0 fw-normal text-dark\">Your order is placed</h6>\r\n");
      out.write("                                                <small class=\"text-muted mb-0\">Dummy text of the printing and industry.</small>\r\n");
      out.write("                                            </div><!--end media-body-->\r\n");
      out.write("                                        </div><!--end media-->\r\n");
      out.write("                                    </a><!--end-item-->\r\n");
      out.write("                                    <!-- item-->\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item py-3\">\r\n");
      out.write("                                        <small class=\"float-end text-muted ps-2\">10 min ago</small>\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <div class=\"avatar-md bg-soft-primary\">\r\n");
      out.write("                                                <img src=\"assets/images/users/user-4.jpg\" alt=\"\" class=\"thumb-sm rounded-circle\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body align-self-center ms-2 text-truncate\">\r\n");
      out.write("                                                <h6 class=\"my-0 fw-normal text-dark\">Meeting with designers</h6>\r\n");
      out.write("                                                <small class=\"text-muted mb-0\">It is a long established fact that a reader.</small>\r\n");
      out.write("                                            </div><!--end media-body-->\r\n");
      out.write("                                        </div><!--end media-->\r\n");
      out.write("                                    </a><!--end-item-->\r\n");
      out.write("                                    <!-- item-->\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item py-3\">\r\n");
      out.write("                                        <small class=\"float-end text-muted ps-2\">40 min ago</small>\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <div class=\"avatar-md bg-soft-primary\">                                                    \r\n");
      out.write("                                                <i data-feather=\"users\" class=\"align-self-center icon-xs\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body align-self-center ms-2 text-truncate\">\r\n");
      out.write("                                                <h6 class=\"my-0 fw-normal text-dark\">UX 3 Task complete.</h6>\r\n");
      out.write("                                                <small class=\"text-muted mb-0\">Dummy text of the printing.</small>\r\n");
      out.write("                                            </div><!--end media-body-->\r\n");
      out.write("                                        </div><!--end media-->\r\n");
      out.write("                                    </a><!--end-item-->\r\n");
      out.write("                                    <!-- item-->\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item py-3\">\r\n");
      out.write("                                        <small class=\"float-end text-muted ps-2\">1 hr ago</small>\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <div class=\"avatar-md bg-soft-primary\">\r\n");
      out.write("                                                <img src=\"assets/images/users/user-5.jpg\" alt=\"\" class=\"thumb-sm rounded-circle\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body align-self-center ms-2 text-truncate\">\r\n");
      out.write("                                                <h6 class=\"my-0 fw-normal text-dark\">Your order is placed</h6>\r\n");
      out.write("                                                <small class=\"text-muted mb-0\">It is a long established fact that a reader.</small>\r\n");
      out.write("                                            </div><!--end media-body-->\r\n");
      out.write("                                        </div><!--end media-->\r\n");
      out.write("                                    </a><!--end-item-->\r\n");
      out.write("                                    <!-- item-->\r\n");
      out.write("                                    <a href=\"#\" class=\"dropdown-item py-3\">\r\n");
      out.write("                                        <small class=\"float-end text-muted ps-2\">2 hrs ago</small>\r\n");
      out.write("                                        <div class=\"media\">\r\n");
      out.write("                                            <div class=\"avatar-md bg-soft-primary\">\r\n");
      out.write("                                                <i data-feather=\"check-circle\" class=\"align-self-center icon-xs\"></i>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"media-body align-self-center ms-2 text-truncate\">\r\n");
      out.write("                                                <h6 class=\"my-0 fw-normal text-dark\">Payment Successfull</h6>\r\n");
      out.write("                                                <small class=\"text-muted mb-0\">Dummy text of the printing.</small>\r\n");
      out.write("                                            </div><!--end media-body-->\r\n");
      out.write("                                        </div><!--end media-->\r\n");
      out.write("                                    </a><!--end-item-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- All-->\r\n");
      out.write("                                <a href=\"javascript:void(0);\" class=\"dropdown-item text-center text-primary\">\r\n");
      out.write("                                    View all <i class=\"fi-arrow-right\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <li class=\"dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle waves-effect waves-light nav-user\" data-bs-toggle=\"dropdown\" href=\"#\" role=\"button\"\r\n");
      out.write("                                aria-haspopup=\"false\" aria-expanded=\"false\">\r\n");
      out.write("                                <span class=\"ms-1 nav-user-name hidden-sm\">Admin</span>\r\n");
      out.write("                                <img src=\"assets/images/users/user-5.jpg\" alt=\"profile-user\" class=\"rounded-circle thumb-xs\" />                                 \r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("                              \r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"Logout.jsp\"><i data-feather=\"power\" class=\"align-self-center icon-xs icon-dual me-1\"></i> Logout</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul><!--end topbar-nav-->\r\n");
      out.write("        \r\n");
      out.write("                    <ul class=\"list-unstyled topbar-nav mb-0\">                        \r\n");
      out.write("                        <li>\r\n");
      out.write("                            <button class=\"nav-link button-menu-mobile\">\r\n");
      out.write("                                <i data-feather=\"menu\" class=\"align-self-center topbar-icon\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </li> \r\n");
      out.write("                                             \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- end navbar-->\r\n");
      out.write("            </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
